"""
Django settings for Hello_IT_mysite project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'l8m!o-(b2q02dcxj_q&h7c&j577n7q^y@4ged#4ptwzdax0mkg'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'l8m!o-(b2q02dcxj_q&h7c&j577n7q^y@4ged#4ptwzdax0mkg')

# SECURITY WARNING: don't run with debug turned on in production!
# Usuń znacznik komentarza z DEBUG=True i dodaj do DEBUG=False, jeśli testujesz na serwerze lokalnym.
# NIE ZAPOMNIJ PRZYWRÓCIĆ TEGO DO DOMYŚLNYCH WARTOŚCI KIEDY ROBISZ COMMITA!
DEBUG = True
#DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'hello-it.herokuapp.com','localhost', '192.168.1.163']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Hello_IT_Blog',
    'members',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Hello_IT_mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hello_IT_mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'CONN_MAX_AGE': 500,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'pl-pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = 'Hello_IT_mysite/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Hello_IT_mysite/media/')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'Hello_IT_Blog/static'),
)

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# EMAIL SETTINGS
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'hit.helloit@gmail.com'
EMAIL_HOST_PASSWORD = 'gctk pero kudi vlpy'
EMAIL_USE_TLS = False


# Heroku - podpięcie pod bazę
prod_db = dj_database_url.config(conn_max_age=500, ssl_require=True)
DATABASES['default'].update(prod_db)

# Jeśli zamierzasz bawić się na serwerze lokalnym, usuń komentarze z górnych i dodaj je do dolnych.
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True
# NIE ZAPOMNIJ ICH PRZYWRÓCIĆ DO POPRZEDNIEGO STANU KIEDY ROBISZ COMMITA!

LOGIN_REDIRECT_URL = 'home_page'
LOGOUT_REDIRECT_URL = 'home_page'


# Jeśli zamierzasz bawić się na serwerze lokalnym, to:
# Usuń tutaj komentarz:
SECURE_SSL_REDIRECT = False
# Dodaj komentarz tutaj:
#SECURE_SSL_REDIRECT = True
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# NIE ZAPOMNIJ ICH PRZYWRÓCIĆ DO POPRZEDNIEGO STANU KIEDY ROBISZ COMMITA!
