# Generated by Django 3.1.6 on 2021-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0002_post_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=255)),
                ('about_header_image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
