# Generated by Django 3.1.6 on 2021-02-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0004_about_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=30)),
                ('people_surname', models.CharField(max_length=50)),
                ('people_photo', models.ImageField(blank=True, null=True, upload_to='img/people')),
                ('people_hobby', models.CharField(max_length=255)),
                ('people_position', models.CharField(max_length=255)),
                ('people_info', models.TextField(default='')),
            ],
        ),
    ]
