# Generated by Django 3.1.6 on 2021-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0005_aboutpeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpeople',
            name='people_photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/people/'),
        ),
    ]
