# Generated by Django 3.1.6 on 2021-02-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0006_auto_20210215_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
