# Generated by Django 3.1.6 on 2021-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0007_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpeople',
            name='people_tag',
            field=models.CharField(default='C#', max_length=20),
            preserve_default=False,
        ),
    ]
