# Generated by Django 3.1.6 on 2021-02-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0008_aboutpeople_people_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPeople',
            new_name='People',
        ),
    ]
