# Generated by Django 3.1.6 on 2021-03-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0010_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about_div_id',
            new_name='div_id',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about_title',
            new_name='title',
        ),
    ]
