# Generated by Django 3.1.6 on 2021-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0011_auto_20210310_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/our_projects/')),
                ('project_name', models.CharField(max_length=100)),
                ('creators_names', models.TextField(default='')),
                ('short_info', models.CharField(max_length=130)),
                ('full_info', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/people_projects/')),
                ('project_name', models.CharField(max_length=100)),
                ('creators_names', models.TextField(default='')),
                ('short_info', models.CharField(max_length=130)),
                ('full_info', models.TextField(default='')),
            ],
        ),
    ]
