# Generated by Django 3.1.6 on 2021-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0012_ourproject_peopleproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproject',
            name='project_div_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopleproject',
            name='project_div_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
