# Generated by Django 3.1.7 on 2021-03-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0013_auto_20210323_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_tag',
            field=models.CharField(choices=[('csharp', 'C#'), ('python', 'Python'), ('java', 'Java'), ('php', 'PHP'), ('js', 'JavaScript')], default='csharp', max_length=20),
        ),
    ]
