# Generated by Django 3.1.6 on 2021-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0014_auto_20210327_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='div_id',
            field=models.CharField(help_text='Maks. 20 znaków, małe litery, zamiast spacji podkreślniki. Musi być unikatowy.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text='Maks. 50 znaków', max_length=50),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='project_div_id',
            field=models.CharField(help_text='Maks. 20 znaków, małe litery, zamiast spacji podkreślniki. Musi być unikatowy.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='project_name',
            field=models.CharField(help_text='Maks. 100 znaków', max_length=100),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='short_info',
            field=models.CharField(help_text='Maks. 130 znaków', max_length=130),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_hobby',
            field=models.CharField(help_text='Maks. 255 znaków', max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_name',
            field=models.CharField(help_text='Maks. 30 znaków', max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_position',
            field=models.CharField(help_text='Maks. 255 znaków', max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_surname',
            field=models.CharField(help_text='Maks. 50 znaków', max_length=50),
        ),
        migrations.AlterField(
            model_name='peopleproject',
            name='project_div_id',
            field=models.CharField(help_text='Maks. 20 znaków, małe litery, zamiast spacji podkreślniki. Musi być unikatowy', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='peopleproject',
            name='project_name',
            field=models.CharField(help_text='Maks. 100 znaków', max_length=100),
        ),
        migrations.AlterField(
            model_name='peopleproject',
            name='short_info',
            field=models.CharField(help_text='Maks. 130 znaków', max_length=130),
        ),
    ]
