# Generated by Django 3.1.6 on 2021-04-02 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0015_auto_20210327_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproject',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Automatycznie aktualizowane, nie ruszać'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopleproject',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='peopleproject',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Automatycznie aktualizowane, nie ruszać'),
            preserve_default=False,
        ),
    ]
