# Generated by Django 3.1.6 on 2021-04-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0016_auto_20210402_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleproject',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='Automatycznie aktualizowane, nie ruszać'),
        ),
    ]
