# Generated by Django 3.1.6 on 2021-04-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0017_auto_20210402_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_tag',
            field=models.CharField(choices=[('C#', (('rppg', 'Team RPPG'), ('racing', 'Team Racing'), ('brawl', 'Team Brawl'))), ('Python', (('django', 'Team Django'),)), ('Java', (('java1', 'Team Java 1'),)), ('PHP', (('php1', 'Team PHP 1'),)), ('JavaScript', (('js1', 'Team JavaScript 1'),))], default='rppg', max_length=20),
        ),
    ]
