# Generated by Django 3.1.6 on 2021-04-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0018_auto_20210408_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourproject',
            old_name='img',
            new_name='banner_img',
        ),
        migrations.RenameField(
            model_name='peopleproject',
            old_name='img',
            new_name='banner_img',
        ),
    ]
