# Generated by Django 3.1.6 on 2021-04-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0019_auto_20210409_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproject',
            name='full_info',
        ),
        migrations.CreateModel(
            name='PeopleProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/our_projects/<django.db.models.query_utils.DeferredAttribute object at 0x000002527ED91CF8>/')),
                ('img_title', models.CharField(blank=True, default='', help_text='Podpis pod zdjęciem, maks. 140 znaków.Jeśli nie dajesz zdjęcia - możesz to zostawić puste', max_length=140)),
                ('paragraph', models.TextField(blank=True, default='', help_text='Tekst, który będzie pojawiać się pod obrazkiem i jego podpisem.Jeśli chcesz zostawic sam obrazek - możesz pominąć to pole.')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.peopleproject')),
            ],
        ),
        migrations.CreateModel(
            name='OurProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/our_projects/<django.db.models.query_utils.DeferredAttribute object at 0x000002527ED91CF8>/')),
                ('img_title', models.CharField(blank=True, default='', help_text='Podpis pod zdjęciem, maks. 140 znaków.Jeśli nie dajesz zdjęcia - możesz to zostawić puste', max_length=140)),
                ('paragraph', models.TextField(blank=True, default='', help_text='Tekst, który będzie pojawiać się pod obrazkiem i jego podpisem.Jeśli chcesz zostawic sam obrazek - możesz pominąć to pole.')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.ourproject')),
            ],
        ),
    ]
