# Generated by Django 3.1.6 on 2021-04-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0020_auto_20210409_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprojectdata',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/our_projects/data/'),
        ),
        migrations.AlterField(
            model_name='peopleprojectdata',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/people_projects/data/'),
        ),
    ]
