# Generated by Django 3.1.6 on 2021-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0021_auto_20210409_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproject',
            name='creators_names',
        ),
        migrations.AddField(
            model_name='ourproject',
            name='team',
            field=models.CharField(choices=[('C#', (('rppg', 'Team RPPG'), ('racing', 'Team Racing'), ('brawl', 'Team Brawl'))), ('Python', (('django', 'Team Django'),)), ('Java', (('java1', 'Team Java 1'),)), ('PHP', (('php1', 'Team PHP 1'),)), ('JavaScript', (('js1', 'Team JavaScript 1'),))], default='rppg', help_text='Nazwa zespołu nie może przekraczać 30 znaków.', max_length=30),
        ),
    ]
