# Generated by Django 3.1.6 on 2021-04-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0022_auto_20210409_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourproject',
            old_name='team',
            new_name='team_name',
        ),
    ]
