# Generated by Django 3.1.6 on 2021-04-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0023_auto_20210409_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproject',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/our_projects/'),
        ),
        migrations.AddField(
            model_name='peopleproject',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/our_projects/'),
        ),
    ]
