# Generated by Django 3.1.6 on 2021-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0024_auto_20210409_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourproject',
            name='banner_img',
            field=models.ImageField(help_text='Baner na górze szczegółów projektu. Wysokość 400px.', null=True, upload_to='img/our_projects/'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='preview_img',
            field=models.ImageField(help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.', null=True, upload_to='img/our_projects/'),
        ),
        migrations.AlterField(
            model_name='peopleproject',
            name='banner_img',
            field=models.ImageField(help_text='Baner na górze szczegółów projektu. Wysokość 400px.', null=True, upload_to='img/people_projects/'),
        ),
        migrations.AlterField(
            model_name='peopleproject',
            name='preview_img',
            field=models.ImageField(help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.', null=True, upload_to='img/our_projects/'),
        ),
    ]
