# Generated by Django 3.1.6 on 2021-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0025_auto_20210409_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
