# Generated by Django 3.1.6 on 2021-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0026_auto_20210412_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.TextField(default='', help_text='Wysokość 150px.'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='banner_img',
            field=models.TextField(default='', help_text='Baner na górze szczegółów projektu. Wysokość 400px.'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='preview_img',
            field=models.TextField(default='', help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.'),
        ),
        migrations.AlterField(
            model_name='ourprojectdata',
            name='img',
            field=models.TextField(blank=True, default='', help_text='To samo się skaluje.'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_photo',
            field=models.TextField(default='', help_text='Wymiary min. 492px x 633px'),
        ),
        migrations.AlterField(
            model_name='peopleproject',
            name='banner_img',
            field=models.TextField(default='', help_text='Baner na górze szczegółów projektu. Wysokość 400px.'),
        ),
        migrations.AlterField(
            model_name='peopleproject',
            name='preview_img',
            field=models.TextField(default='', help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.'),
        ),
        migrations.AlterField(
            model_name='peopleprojectdata',
            name='img',
            field=models.TextField(blank=True, default='', help_text='To samo się skaluje.'),
        ),
    ]
