# Generated by Django 3.1.6 on 2021-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0028_auto_20210412_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='')),
                ('div_id', models.CharField(default='', max_length=20)),
                ('rules_group', models.CharField(choices=[('members', 'Członkowie koła'), ('guests', 'Goście koła')], default='members', max_length=15)),
            ],
        ),
    ]
