# Generated by Django 3.1.6 on 2021-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0031_auto_20210416_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type_regulations', models.CharField(choices=[('members', 'Members'), ('right_members', 'Right_members'), ('responsibilities_members', 'Responsibilities_members'), ('effect_members', 'Effect_members'), ('guests', 'Guests'), ('right_guests', 'Right_guests'), ('responsibilities_guests', 'Responsibilities_guests'), ('effect_guests', 'Effect_guests'), ('none', 'None')], default='members', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='brak', max_length=255),
        ),
    ]
