# Generated by Django 3.1.6 on 2021-04-17 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0032_auto_20210416_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.TextField(default='', help_text='Baner na górze szczegółów projektu. Wysokość 400px.')),
                ('preview_img', models.TextField(default='', help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.')),
                ('project_name', models.CharField(help_text='Maks. 100 znaków', max_length=100)),
                ('team_name', models.CharField(choices=[('rppg', 'Team RPPG'), ('racing', 'Team Racing'), ('brawl', 'Team Darkest Kombat'), ('django', 'Team Django'), ('individual', 'Projekt Indywidualny')], default='rppg', help_text='Nazwa zespołu nie może przekraczać 30 znaków.', max_length=30)),
                ('creators_name', models.TextField(blank=True, default='', help_text='Wypełnij tylko kiedy wybrałeś jako drużynę "Projekt Indywidualny"', null=True)),
                ('short_info', models.CharField(help_text='Maks. 130 znaków', max_length=130)),
                ('project_div_id', models.CharField(help_text='Maks. 20 znaków, małe litery, zamiast spacji podkreślniki. Musi być unikatowy.', max_length=20, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now_add=True, help_text='Automatycznie aktualizowane, nie ruszać')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(blank=True, default='', help_text='To samo się skaluje.')),
                ('img_title', models.CharField(blank=True, default='', help_text='Podpis pod zdjęciem, maks. 140 znaków.Jeśli nie dajesz zdjęcia - możesz to zostawić puste', max_length=140)),
                ('paragraph', models.TextField(blank=True, default='', help_text='Tekst, który będzie pojawiać się pod obrazkiem i jego podpisem.Jeśli chcesz zostawic sam obrazek - możesz pominąć to pole.')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='ourprojectdata',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='peopleprojectdata',
            name='reference',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.AlterField(
            model_name='people',
            name='people_tag',
            field=models.CharField(choices=[('rppg', 'Team RPPG'), ('racing', 'Team Racing'), ('brawl', 'Team Darkest Kombat'), ('django', 'Team Django'), ('overseer', 'Opiekun Koła')], default='rppg', max_length=20),
        ),
        migrations.DeleteModel(
            name='OurProject',
        ),
        migrations.DeleteModel(
            name='OurProjectData',
        ),
        migrations.DeleteModel(
            name='PeopleProject',
        ),
        migrations.DeleteModel(
            name='PeopleProjectData',
        ),
    ]
