# Generated by Django 3.1.6 on 2021-04-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0033_auto_20210417_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='help_title',
            field=models.CharField(default='', help_text='Pomocniczy tytuł do odnoszenia się w bazie. Max. 50 znaków', max_length=50),
        ),
    ]
