# Generated by Django 3.1.6 on 2021-04-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0034_projectdata_help_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='reference',
            field=models.ForeignKey(help_text='Wybierz do którego postu chcesz dodać sekcję', on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.project'),
        ),
    ]
