# Generated by Django 3.1.6 on 2021-05-26 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0035_auto_20210418_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_hobby',
            field=models.CharField(help_text='Maks. 255 znaków', max_length=255, verbose_name='Zainteresowania'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_info',
            field=models.TextField(default='', verbose_name='Informacje'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_name',
            field=models.CharField(help_text='Maks. 30 znaków', max_length=30, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_photo',
            field=models.TextField(default='', help_text='Wymiary min. 492px x 633px', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_position',
            field=models.CharField(help_text='Maks. 255 znaków', max_length=255, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_surname',
            field=models.CharField(help_text='Maks. 50 znaków', max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_tag',
            field=models.CharField(choices=[('rppg', 'Team RPPG'), ('racing', 'Team Racing'), ('brawl', 'Team Darkest Kombat'), ('django', 'Team Django'), ('overseer', 'Opiekun Koła')], default='rppg', max_length=20, verbose_name='Drużyna'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='brak', max_length=255, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.TextField(blank=True, null=True, verbose_name='Baner'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner_img',
            field=models.TextField(default='', help_text='Baner na górze szczegółów projektu. Wysokość 400px.', verbose_name='Baner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creators_name',
            field=models.TextField(blank=True, default='', help_text='Wypełnij tylko kiedy wybrałeś jako drużynę "Projekt Indywidualny"', null=True, verbose_name='Twórca'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_img',
            field=models.TextField(default='', help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.', verbose_name='Miniaturka'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_div_id',
            field=models.CharField(help_text='Maks. 20 znaków, małe litery, zamiast spacji podkreślniki. Musi być unikatowy.', max_length=20, unique=True, verbose_name='ID HTML'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(help_text='Maks. 100 znaków', max_length=100, verbose_name='Nazwa projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_info',
            field=models.CharField(help_text='Maks. 130 znaków', max_length=130, verbose_name='Krótka informacja'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_name',
            field=models.CharField(choices=[('rppg', 'Team RPPG'), ('racing', 'Team Racing'), ('brawl', 'Team Darkest Kombat'), ('django', 'Team Django'), ('individual', 'Projekt Indywidualny')], default='rppg', help_text='Nazwa zespołu nie może przekraczać 30 znaków.', max_length=30, verbose_name='Drużyna'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Automatycznie aktualizowane, nie ruszać', verbose_name='Aktualizacja'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='help_title',
            field=models.CharField(default='', help_text='Pomocniczy tytuł do odnoszenia się w bazie. Max. 50 znaków', max_length=50, verbose_name='Tytuł pomocniczy'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='img',
            field=models.TextField(blank=True, default='', help_text='To samo się skaluje.', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='img_title',
            field=models.CharField(blank=True, default='', help_text='Podpis pod zdjęciem, maks. 140 znaków. Jeśli nie dajesz zdjęcia - możesz to zostawić puste', max_length=140, verbose_name='Podpis pod obrazkiem'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='paragraph',
            field=models.TextField(blank=True, default='', help_text='Tekst, który będzie pojawiać się pod obrazkiem i jego podpisem.Jeśli chcesz zostawic sam obrazek - możesz pominąć to pole.', verbose_name='Akapit'),
        ),
    ]
