# Generated by Django 3.1.6 on 2021-06-11 11:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0040_auto_20210611_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_field',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique_with=('pk',)),
        ),
    ]
