# Generated by Django 3.1.6 on 2021-06-11 12:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0041_auto_20210611_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug_field',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='project_name', unique_with=('date',)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_field',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique_with=('published_date',)),
        ),
    ]
