# Generated by Django 3.1.6 on 2021-09-28 10:02

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0042_auto_20210611_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.TextField(default='', help_text='Baner na górze szczegółów projektu. Wysokość 400px.', verbose_name='Baner')),
                ('preview_img', models.TextField(default='', help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.', verbose_name='Miniaturka')),
                ('project_name', models.CharField(help_text='Maks. 100 znaków', max_length=100, verbose_name='Nazwa projektu')),
                ('creators_name', models.TextField(blank=True, default='', help_text='Twórcy projektu', null=True, verbose_name='Twórca')),
                ('short_info', models.CharField(help_text='Maks. 130 znaków', max_length=130, verbose_name='Krótka informacja')),
                ('project_div_id', models.CharField(help_text='Maks. 20 znaków, małe litery, zamiast spacji podkreślniki. Musi być unikatowy.', max_length=20, unique=True, verbose_name='ID HTML')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('update_date', models.DateTimeField(auto_now_add=True, help_text='Automatycznie aktualizowane, nie ruszać', verbose_name='Aktualizacja')),
                ('slug_field', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='project_name', unique_with=('date',))),
            ],
            options={
                'verbose_name': 'Projekt Indywidualny',
                'verbose_name_plural': 'Projekty Indywidualne',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='creators_name',
        ),
        migrations.CreateModel(
            name='IndividualProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(blank=True, default='', help_text='To samo się skaluje.', verbose_name='Obrazek')),
                ('img_title', models.CharField(blank=True, default='', help_text='Podpis pod zdjęciem, maks. 140 znaków. Jeśli nie dajesz zdjęcia - możesz to zostawić puste', max_length=140, verbose_name='Podpis pod obrazkiem')),
                ('paragraph', models.TextField(blank=True, default='', help_text='Tekst, który będzie pojawiać się pod obrazkiem i jego podpisem.Jeśli chcesz zostawic sam obrazek - możesz pominąć to pole.', verbose_name='Akapit')),
                ('help_title', models.CharField(default='', help_text='Pomocniczy tytuł do odnoszenia się w bazie. Max. 50 znaków', max_length=50, verbose_name='Tytuł pomocniczy')),
                ('reference', models.ForeignKey(help_text='Wybierz do którego postu chcesz dodać sekcję', on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.individualproject')),
            ],
            options={
                'verbose_name': 'Podpunkt Indywidualnego Projektu',
                'verbose_name_plural': 'Podpunkty Indywidualnych Projektów',
            },
        ),
    ]
