# Generated by Django 3.1.6 on 2021-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0043_auto_20210928_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_name',
            field=models.CharField(choices=[('rppg', 'Team RPPG'), ('racing', 'Team Racing'), ('brawl', 'Team Darkest Kombat'), ('django', 'Team Django')], default='rppg', help_text='Nazwa zespołu nie może przekraczać 30 znaków.', max_length=30, verbose_name='Drużyna'),
        ),
    ]
