# Generated by Django 3.1.6 on 2022-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0044_auto_20210928_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_photo',
            field=models.TextField(blank=True, default='', help_text='Wymiary min. 492px x 633px, zostaw puste dla domyślnego zdjęcia', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_tag',
            field=models.CharField(choices=[('rppg', 'Team RPPG'), ('python', 'Grupa Python'), ('flutter', 'Team Flutter'), ('unitya', 'Grupa Unity A'), ('unityb', 'Grupa Unity B'), ('overseer', 'Opiekun Koła')], default='rppg', max_length=20, verbose_name='Drużyna'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_name',
            field=models.CharField(choices=[('rppg', 'Team RPPG'), ('python', 'Grupa Python'), ('flutter', 'Team Flutter'), ('unitya', 'Grupa Unity A'), ('unityb', 'Grupa Unity B')], default='rppg', help_text='Nazwa zespołu nie może przekraczać 30 znaków.', max_length=30, verbose_name='Drużyna'),
        ),
    ]
