# Generated by Django 3.1.6 on 2022-02-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0046_people_people_position_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_founder',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeśli osoba ta jest jednym z założycieli koła', verbose_name='"Ojciec Założyciel"'),
        ),
    ]
