# Generated by Django 3.1.6 on 2022-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0047_people_is_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='is_founder',
            field=models.BooleanField(default=False, verbose_name='"Ojciec Założyciel"'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_hobby',
            field=models.CharField(blank=True, help_text='Maks. 255 znaków', max_length=255, verbose_name='Zainteresowania'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_info',
            field=models.TextField(blank=True, default='', verbose_name='Informacje'),
        ),
    ]
