# Generated by Django 3.1.6 on 2022-03-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0050_auto_20220310_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegulationsSectionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionData', models.CharField(max_length=255, verbose_name='Treść')),
                ('SectionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.regulationssection')),
            ],
        ),
    ]
