# Generated by Django 3.1.6 on 2022-03-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0051_regulationssection_regulationssectiondetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegulationsSectionDetails',
            new_name='RegulationsSectionDetail',
        ),
    ]
