# Generated by Django 3.1.6 on 2022-03-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0052_auto_20220318_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regulation',
        ),
        migrations.AlterModelOptions(
            name='regulationssection',
            options={'verbose_name': 'Sekcje Regulaminu', 'verbose_name_plural': 'Regulamin'},
        ),
    ]
