# Generated by Django 3.1.14 on 2022-03-24 14:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0053_auto_20220322_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(blank=True, default='', help_text='To samo się skaluje.', verbose_name='Obrazek')),
                ('help_title', models.CharField(default='', help_text='Pomocniczy tytuł do bazy danychMax. 50 znaków', max_length=50, verbose_name='Tytuł pomocniczy')),
            ],
            options={
                'verbose_name': 'Zdjęcie do innego projektu',
                'verbose_name_plural': 'Zdjęcia do innego projektu',
            },
        ),
        migrations.CreateModel(
            name='OtherProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.TextField(default='', help_text='Baner na górze szczegółów projektu. Wysokość 400px.', verbose_name='Baner')),
                ('preview_img', models.TextField(default='', help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.', verbose_name='Miniaturka')),
                ('project_name', models.CharField(help_text='Maks. 100 znaków', max_length=100, verbose_name='Nazwa projektu')),
                ('creators_name', models.TextField(blank=True, default='', help_text='Twórcy projektu', null=True, verbose_name='Twórca')),
                ('short_info', models.CharField(help_text='Maks. 130 znaków', max_length=130, verbose_name='Krótka informacja')),
                ('project_div_id', models.CharField(help_text='Maks. 20 znaków, małe litery, zamiast spacji podkreślniki. Musi być unikatowy.', max_length=20, unique=True, verbose_name='ID HTML')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('update_date', models.DateTimeField(auto_now_add=True, help_text='Automatycznie aktualizowane, nie ruszać', verbose_name='Aktualizacja')),
                ('slug_field', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='project_name', unique_with=('date',))),
            ],
            options={
                'verbose_name': 'Projekt Indywidualny',
                'verbose_name_plural': 'Projekty Indywidualne',
            },
        ),
        migrations.CreateModel(
            name='ProjectImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(default='', help_text='To samo się skaluje.', verbose_name='Obrazek')),
                ('help_title', models.TextField(default='', help_text='Pomocniczy tytuł do bazy danych. Max. 50 znaków', max_length=50, verbose_name='Nazwa obrazka')),
                ('reference', models.ForeignKey(help_text='Wybierz do którego postu chcesz dodać sekcję', on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.project')),
            ],
            options={
                'verbose_name': 'Zdjęcie do projektu',
                'verbose_name_plural': 'Zdjęcia do projektu',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=30, verbose_name='Nazwa drużyny')),
            ],
        ),
        migrations.RemoveField(
            model_name='individualprojectdata',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='reference',
        ),
        migrations.AddField(
            model_name='people',
            name='is_overseer',
            field=models.BooleanField(default=False, verbose_name='Opiekun Koła'),
        ),
        migrations.DeleteModel(
            name='IndividualProject',
        ),
        migrations.DeleteModel(
            name='IndividualProjectData',
        ),
        migrations.DeleteModel(
            name='ProjectData',
        ),
        migrations.AddField(
            model_name='otherimg',
            name='reference',
            field=models.ForeignKey(help_text='Wybierz do którego postu chcesz dodać sekcję', on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.otherproject'),
        ),
    ]
