# Generated by Django 3.1.14 on 2022-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0055_auto_20220324_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Drużyna', 'verbose_name_plural': 'Drużyny'},
        ),
        migrations.AlterField(
            model_name='otherimg',
            name='img',
            field=models.CharField(blank=True, default='', help_text='To samo się skaluje.', max_length=255, verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='projectimg',
            name='help_title',
            field=models.CharField(default='', help_text='Pomocniczy tytuł do bazy danych. Max. 50 znaków', max_length=50, verbose_name='Nazwa obrazka'),
        ),
        migrations.AlterField(
            model_name='projectimg',
            name='img',
            field=models.CharField(default='', help_text='To samo się skaluje.', max_length=255, verbose_name='Obrazek'),
        ),
    ]
