# Generated by Django 3.1.14 on 2022-04-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0056_auto_20220325_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(default='', max_length=50, verbose_name='Stanowisko')),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.RemoveField(
            model_name='otherproject',
            name='project_div_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_div_id',
        ),
        migrations.AlterField(
            model_name='otherproject',
            name='creators_name',
            field=models.TextField(blank=True, default='', help_text='Twórcy projektu', null=True, verbose_name='Twórca(y)'),
        ),
        migrations.AlterField(
            model_name='otherproject',
            name='short_info',
            field=models.CharField(blank=True, help_text='Maks. 130 znaków', max_length=130, null=True, verbose_name='Krótka informacja'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(db_column='Kategoria', on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_info',
            field=models.CharField(blank=True, help_text='Maks. 130 znaków', max_length=130, null=True, verbose_name='Krótka informacja'),
        ),
    ]
