# Generated by Django 3.1.14 on 2022-04-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0058_auto_20220401_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.category', verbose_name='Kategoria'),
        ),
    ]
