# Generated by Django 3.1.14 on 2022-04-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0059_auto_20220401_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(default='', max_length=50, unique=True, verbose_name='Stanowisko')),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
        migrations.RemoveField(
            model_name='people',
            name='people_position_list',
        ),
        migrations.RemoveField(
            model_name='people',
            name='people_tag',
        ),
        migrations.AddField(
            model_name='people',
            name='people_team',
            field=models.ForeignKey(blank=True, db_column='Drużyny', null=True, on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Nazwa drużyny'),
        ),
        migrations.AddField(
            model_name='people',
            name='people_position',
            field=models.ForeignKey(blank=True, db_column='Stanowisko', null=True, on_delete=django.db.models.deletion.CASCADE, to='Hello_IT_Blog.position'),
        ),
    ]
