# Generated by Django 3.2.7 on 2022-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0061_auto_20220401_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank='True', null=True, upload_to=''),
        ),
    ]
