# Generated by Django 3.2.7 on 2022-04-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0062_category_icon'),
        ('Hello_IT_Blog', '0063_alter_post_header_image'),
    ]

    operations = [
    ]
