# Generated by Django 3.2.7 on 2022-04-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_IT_Blog', '0064_merge_0062_category_icon_0063_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank='True', help_text='Wysokość 150px.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='otherimg',
            name='img',
            field=models.ImageField(blank=True, default='', help_text='To samo się skaluje.', max_length=255, null=True, upload_to='', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='otherproject',
            name='banner_img',
            field=models.ImageField(blank='True', default='', help_text='Baner na górze szczegółów projektu. Wysokość 400px.', null=True, upload_to='', verbose_name='Baner'),
        ),
        migrations.AlterField(
            model_name='otherproject',
            name='preview_img',
            field=models.ImageField(blank='True', default='', help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.', null=True, upload_to='', verbose_name='Miniaturka'),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_photo',
            field=models.ImageField(blank='True', help_text='Wymiary min. 492px x 633px', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner_img',
            field=models.ImageField(blank='True', default='', help_text='Baner na górze szczegółów projektu. Wysokość 400px.', null=True, upload_to='', verbose_name='Baner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_img',
            field=models.ImageField(blank='True', default='', help_text='Grafika na kafelku projektu. Szer. 350px, wys. 200px.', null=True, upload_to='', verbose_name='Miniaturka'),
        ),
        migrations.AlterField(
            model_name='projectimg',
            name='img',
            field=models.ImageField(blank='True', default='', help_text='To samo się skaluje.', max_length=255, null=True, upload_to='', verbose_name='Obrazek'),
        ),
    ]
